version: '3.8'

services:

  zookeeper-kaf:

    image: bitnami/zookeeper
    container_name: zookeeper-kaf
    env_file: .env
    ports:
      - "${ZK_PORT}:2181"
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - kafka-learn

  kafka-kaf:

    image: bitnami/kafka
    container_name: kafka-kaf
    depends_on:
      - zookeeper-kaf
    env_file: .env
    ports:
      - "${KAFKA_PORT}:9092"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - kafka-learn

  kafka-ui-kaf:

    container_name: kafka-ui-kaf
    image: provectuslabs/kafka-ui:latest
    env_file: .env
    depends_on:
      - kafka-kaf
    ports:
      - "${KAFKA_UI_PORT}:8080"
    volumes:
      - ./kaf/config.yml:/etc/kafkaui/dynamic_config.yaml

  api-kaf:
    image: api-kaf
    container_name: api-kaf
    ports:
      - "8392:8000"
    env_file: .env
    depends_on:
      - kafka-kaf
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
      context: ./api-kaf
      dockerfile: dockerfile
    volumes:
      - ./api-kaf/app:/app
    networks:
      - kafka-learn

  proc-kaf:
    image: proc-kaf
    container_name: proc-kaf
    env_file: .env
    depends_on:
      - kafka-kaf
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
      context: ./proc-kaf
      dockerfile: dockerfile
    volumes:
      - ./proc-kaf/app:/app
    networks:
      - kafka-learn

networks:
  kafka-learn:
