name: kafka-air-redis-learn
services:
  api-kaf:
    build:
      context: /home/kklepikov/_code_/kafka-air-redis-learn/api-kaf
      dockerfile: dockerfile
      args:
        INSTALL_DEV: "true"
    container_name: api-kaf
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-kaf:9092,OUTSIDE://localhost:9093
      KAFKA_CREATE_TOPICS: products:1:1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kaf:2181
      POSTGRES_DB: kafka-learn
      POSTGRES_PASSWORD: greatagain
      POSTGRES_USER: donaldtrump
    image: api-kaf
    networks:
      kafka-learn: null
    ports:
    - mode: ingress
      target: 8000
      published: "8392"
      protocol: tcp
    volumes:
    - type: bind
      source: /home/kklepikov/_code_/kafka-air-redis-learn/api-kaf/app
      target: /app
      bind:
        create_host_path: true
  kafka-kaf:
    container_name: kafka-kaf
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-kaf:9092,OUTSIDE://localhost:9093
      KAFKA_CREATE_TOPICS: products:1:1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kaf:2181
      POSTGRES_DB: kafka-learn
      POSTGRES_PASSWORD: greatagain
      POSTGRES_USER: donaldtrump
    image: wurstmeister/kafka
    networks:
      kafka-learn: null
    ports:
    - mode: ingress
      target: 9092
      published: "9092"
      protocol: tcp
  postgres-kaf:
    container_name: postgres-kaf
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-kaf:9092,OUTSIDE://localhost:9093
      KAFKA_CREATE_TOPICS: products:1:1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kaf:2181
      PGDATA: /data/postgres
      POSTGRES_DB: kafka-learn
      POSTGRES_PASSWORD: greatagain
      POSTGRES_USER: donaldtrump
    image: postgres
    networks:
      kafka-learn: null
    ports:
    - mode: ingress
      target: 5432
      published: "5432"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: volume
      source: postgres-kaf
      target: /data/postgres
      volume: {}
  proc-kaf:
    build:
      context: /home/kklepikov/_code_/kafka-air-redis-learn/proc-kaf
      dockerfile: dockerfile
      args:
        INSTALL_DEV: "true"
    container_name: proc-kaf
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-kaf:9092,OUTSIDE://localhost:9093
      KAFKA_CREATE_TOPICS: products:1:1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kaf:2181
      POSTGRES_DB: kafka-learn
      POSTGRES_PASSWORD: greatagain
      POSTGRES_USER: donaldtrump
    image: proc-kaf
    networks:
      kafka-learn: null
    volumes:
    - type: bind
      source: /home/kklepikov/_code_/kafka-air-redis-learn/proc-kaf/app
      target: /app
      bind:
        create_host_path: true
  zookeeper-kaf:
    container_name: zookeeper-kaf
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-kaf:9092,OUTSIDE://localhost:9093
      KAFKA_CREATE_TOPICS: products:1:1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kaf:2181
      POSTGRES_DB: kafka-learn
      POSTGRES_PASSWORD: greatagain
      POSTGRES_USER: donaldtrump
    image: wurstmeister/zookeeper
    networks:
      kafka-learn: null
    ports:
    - mode: ingress
      target: 2181
      published: "2181"
      protocol: tcp
networks:
  kafka-learn:
    name: kafka-air-redis-learn_kafka-learn
volumes:
  postgres-kaf:
    name: kafka-air-redis-learn_postgres-kaf
