version: '3.8'

services:

  postgres-kaf:

    image: postgres
    container_name: postgres-kaf
    env_file: .kaf.env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres-kaf:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - kafka-learn
    restart: unless-stopped

  zookeeper-kaf:

    image: wurstmeister/zookeeper
    container_name: zookeeper-kaf
    env_file: .kaf.env
    ports:
      - "2181:2181"
    networks:
      - kafka-learn

  kafka-kaf:

    image: wurstmeister/kafka
    container_name: kafka-kaf
    env_file: .kaf.env
    ports:
      - "9092:9092"
    networks:
      - kafka-learn

  api-kaf:
    image: api-kaf
    container_name: api-kaf
    ports:
      - "8392:8000"
    env_file: .kaf.env
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
      context: ./kaf
      dockerfile: api.dockerfile
    volumes:
      - ./kaf/app:/app
    networks:
      - kafka-learn

networks:
  kafka-learn:

volumes:
    postgres-kaf:
